version: '3.8'  # Specify the Docker Compose version
services:
  frontend:
    image: chaitanya751293/mern:frontend-latest
    container_name: frontend-c
    ports:
      - "3000:3000"  # Map port 80 on the host to port 80 on the container
    networks:
      - mern-network
    
  backend:
    image: chaitanya751293/mern:backend-latest
    container_name: backend-container
    ports:
      - "8080:8080"  # Map port 5000 on the host to port 5000 on the container
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge
